/**
 * MCP server adapter
 *
 * Outputs:
 *   generated/mcp/
 *     mcp-manifest.json  — MCP server definition with tools + resources
 *     README.md          — how to run the yes-human MCP server
 *
 * The yes-human MCP server exposes:
 *   Tools:     yes_route, yes_validate, yes_eval_cost, yes_dossier_check
 *   Resources: yes://boot, yes://route-table, yes://agents, yes://workflows
 *
 * No full registries are exposed at startup; resources are fetched on demand.
 */

import { writeGenerated } from '../index.js';

function buildManifest(ctx) {
  return {
    name: 'yes-human',
    version: ctx.version,
    description: ctx.plugin.description,
    tools: [
      {
        name: 'yes_route',
        description:
          'Resolve a task to its best route (agent + workflow + budget band). Pass dry_run:true for a PlanCard without executing.',
        inputSchema: {
          type: 'object',
          required: ['task'],
          properties: {
            task: { type: 'string', description: 'The user task to route' },
            dry_run: { type: 'boolean', default: true }
          }
        }
      },
      {
        name: 'yes_validate',
        description: 'Run full schema + registry + route consistency validation. Returns pass/fail with details.',
        inputSchema: { type: 'object', properties: {} }
      },
      {
        name: 'yes_eval_cost',
        description: 'Check that the boot file is within the startup token budget (target 180, cap 300).',
        inputSchema: { type: 'object', properties: {} }
      },
      {
        name: 'yes_dossier_check',
        description: 'Validate a source dossier for an agent against the promotion gate (staging or production).',
        inputSchema: {
          type: 'object',
          required: ['agent_id'],
          properties: {
            agent_id: { type: 'string', description: 'Agent id e.g. engineering.code-reviewer' },
            gate: { type: 'string', enum: ['staging', 'production'], default: 'production' }
          }
        }
      }
    ],
    resources: [
      {
        uri: 'yes://boot',
        name: 'Yes-human boot text',
        description: 'The minimal startup boot instruction (~69 tokens)',
        mimeType: 'text/markdown'
      },
      {
        uri: 'yes://route-table',
        name: 'Hot route table',
        description: 'Keyword → route_id map (ROUTE_TABLE.min.json)',
        mimeType: 'application/json'
      },
      {
        uri: 'yes://agents',
        name: 'Agent registry',
        description: 'All registered agents (lazy-loaded on route match)',
        mimeType: 'application/json'
      },
      {
        uri: 'yes://workflows',
        name: 'Workflow registry',
        description: 'All registered workflows with inputs/outputs/gates',
        mimeType: 'application/json'
      }
    ],
    generated_at: ctx.generatedAt
  };
}

function buildReadme(ctx) {
  return `# Yes-human MCP Server

yes-human v${ctx.version} — portable low-token agentic control plane.

## Tools

| Tool | Description |
|------|-------------|
| \`yes_route\` | Resolve a task to a route (agent + workflow + budget) |
| \`yes_validate\` | Run full validation suite |
| \`yes_eval_cost\` | Check startup token budget |
| \`yes_dossier_check\` | Validate a source dossier for promotion |

## Resources

| URI | Description |
|-----|-------------|
| \`yes://boot\` | Boot text (~69 tokens) |
| \`yes://route-table\` | Hot keyword → route_id map |
| \`yes://agents\` | Agent registry |
| \`yes://workflows\` | Workflow registry |

## Running

\`\`\`bash
# Add to your MCP config:
# {
#   "mcpServers": {
#     "yes-human": {
#       "command": "node",
#       "args": ["packages/yes-cli/index.js", "mcp"]
#     }
#   }
# }
\`\`\`

_Generated by yes-human adapters v${ctx.version} on ${ctx.generatedAt}_
`;
}

export async function generate(ctx) {
  writeGenerated('mcp', 'mcp-manifest.json', buildManifest(ctx));
  writeGenerated('mcp', 'README.md', buildReadme(ctx));
  console.log('  ✓ mcp bundle generated');
}
